#!/bin/sh
# script/test-oe: Lint recipes in this layer with oelint-adv. Fast and cheap;
# does not require checking out the poky/meta-openembedded submodules.
set -e

cd "$(dirname "$0")/.."

oelint-adv \
    --suppress oelint.var.suggestedvar.CVE_PRODUCT \
    --suppress oelint.var.suggestedvar.SECTION \
    --suppress oelint.var.licenseremotefile \
    meta-genet-python/recipes-*/*/*.bb \
    meta-genet-python/recipes-*/*/*.inc
