name: Lint (oelint-adv)

on:
  push:
    branches: [main]
  pull_request:

jobs:
  oelint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: false

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install oelint-adv
        run: pip install oelint-adv

      - name: Run oelint-adv
        run: |
          oelint-adv \
            --suppress oelint.var.suggestedvar.CVE_PRODUCT \
            --suppress oelint.var.suggestedvar.SECTION \
            --suppress oelint.var.licenseremotefile \
            meta-genet-python/recipes-*/*/*.bb \
            meta-genet-python/recipes-*/*/*.inc
