name: Lint (oelint-adv)

on:
  push:
    branches: [main]
  pull_request:

jobs:
  oelint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: false

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Bootstrap
        run: script/bootstrap-oe

      - name: Test
        run: script/test-oe
